# Development environment configuration
# Optimized for local development with debugging enabled

server:
  host: localhost
  port: 3000
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  max_header_bytes: 1048576  # 1MB

logger:
  level: debug
  format: text
  service: mcp-server
  version: dev