# Docker container configuration
# Optimized for containerized deployment

server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 20s
  write_timeout: 20s
  idle_timeout: 90s
  max_header_bytes: 1048576  # 1MB

logger:
  level: info
  format: json
  service: mcp-server
  version: "docker"

mcp:
  protocol_timeout: 45s
  max_tools: 100
  max_resources: 100
  debug_mode: false
  enable_metrics: true
  buffer_size: 4096